### ISSUE TITLE
Cannot enter spark-shell

### ISSUE THREAD

**Issue by samthebest** [entropyltd/spark-cloud#1]
I successfully launch a cluster, then ssh in, I try getting into the spark shell by the following means and neither work

A

```
spark-submit --master yarn-client
```

B

```
spark-submit
```

causes:

A

```
15/12/03 12:37:02 INFO spark.SecurityManager: Changing view acls to: ubuntu
15/12/03 12:37:02 INFO spark.SecurityManager: Changing modify acls to: ubuntu
15/12/03 12:37:02 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(ubuntu); users with modify permissions: Set(ubuntu)
15/12/03 12:37:02 INFO spark.HttpServer: Starting HTTP Server
15/12/03 12:37:03 INFO server.Server: jetty-8.y.z-SNAPSHOT
15/12/03 12:37:03 INFO server.AbstractConnector: Started SocketConnector@0.0.0.0:44095
15/12/03 12:37:03 INFO util.Utils: Successfully started service 'HTTP class server' on port 44095.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.5.0-cdh5.5.0
      /_/

Using Scala version 2.10.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_45-internal)
Type in expressions to have them evaluated.
Type :help for more information.
15/12/03 12:37:16 INFO spark.SparkContext: Running Spark version 1.5.0-cdh5.5.0
15/12/03 12:37:16 INFO spark.SecurityManager: Changing view acls to: ubuntu
15/12/03 12:37:16 INFO spark.SecurityManager: Changing modify acls to: ubuntu
15/12/03 12:37:16 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(ubuntu); users with modify permissions: Set(ubuntu)
15/12/03 12:37:17 INFO slf4j.Slf4jLogger: Slf4jLogger started
15/12/03 12:37:17 INFO Remoting: Starting remoting
15/12/03 12:37:18 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@172.31.63.191:45209]
15/12/03 12:37:18 INFO Remoting: Remoting now listens on addresses: [akka.tcp://sparkDriver@172.31.63.191:45209]
15/12/03 12:37:18 INFO util.Utils: Successfully started service 'sparkDriver' on port 45209.
15/12/03 12:37:18 INFO spark.SparkEnv: Registering MapOutputTracker
15/12/03 12:37:18 INFO spark.SparkEnv: Registering BlockManagerMaster
15/12/03 12:37:18 INFO storage.DiskBlockManager: Created local directory at /tmp/blockmgr-5cdc96b6-fbbe-4d8b-9b52-be150436503c
15/12/03 12:37:18 INFO storage.MemoryStore: MemoryStore started with capacity 534.5 MB
15/12/03 12:37:19 INFO spark.HttpFileServer: HTTP File server directory is /tmp/spark-291568cb-c8e8-44a4-b51c-329a58174370/httpd-0bebfcfb-c290-44a4-823f-4348b2988bf5
15/12/03 12:37:19 INFO spark.HttpServer: Starting HTTP Server
15/12/03 12:37:19 INFO server.Server: jetty-8.y.z-SNAPSHOT
15/12/03 12:37:19 INFO server.AbstractConnector: Started SocketConnector@0.0.0.0:56929
15/12/03 12:37:19 INFO util.Utils: Successfully started service 'HTTP file server' on port 56929.
15/12/03 12:37:19 INFO spark.SparkEnv: Registering OutputCommitCoordinator
15/12/03 12:37:19 INFO server.Server: jetty-8.y.z-SNAPSHOT
15/12/03 12:37:20 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:4040
15/12/03 12:37:20 INFO util.Utils: Successfully started service 'SparkUI' on port 4040.
15/12/03 12:37:20 INFO ui.SparkUI: Started SparkUI at http://ip-172-31-63-191.ec2.internal:4040
15/12/03 12:37:20 WARN metrics.MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
15/12/03 12:37:20 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032
15/12/03 12:37:22 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:23 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:24 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:25 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:26 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:27 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:28 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:29 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:30 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:37:31 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:38:02 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:38:03 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
15/12/03 12:38:04 INFO ipc.Client: Retrying connect to server: 0.0.0.0/0.0.0.0:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
...
repeats forever
...


```

B

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: java.net.UnknownHostException: cluster
  at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:512)
  at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:171)
  at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:162)
  at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:160)
  at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:167)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
  at org.apache.spark.repl.SparkILoop.createSQLContext(SparkILoop.scala:1028)
  at $iwC$$iwC.<init>(<console>:9)
  at $iwC.<init>(<console>:18)
  at <init>(<console>:20)
  at .<init>(<console>:24)
  at .<clinit>(<console>)
  at .<init>(<console>:7)
  at .<clinit>(<console>)
  at $print(<console>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
  at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1340)
  at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
  at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
  at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
  at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
  at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
  at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
  at org.apache.spark.repl.SparkILoopInit$$anonfun$initializeSpark$1.apply(SparkILoopInit.scala:132)
  at org.apache.spark.repl.SparkILoopInit$$anonfun$initializeSpark$1.apply(SparkILoopInit.scala:124)
  at org.apache.spark.repl.SparkIMain.beQuietDuring(SparkIMain.scala:324)
  at org.apache.spark.repl.SparkILoopInit$class.initializeSpark(SparkILoopInit.scala:124)
  at org.apache.spark.repl.SparkILoop.initializeSpark(SparkILoop.scala:64)
  at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1$$anonfun$apply$mcZ$sp$5.apply$mcV$sp(SparkILoop.scala:974)
  at org.apache.spark.repl.SparkILoopInit$class.runThunks(SparkILoopInit.scala:159)
  at org.apache.spark.repl.SparkILoop.runThunks(SparkILoop.scala:64)
  at org.apache.spark.repl.SparkILoopInit$class.postInitialization(SparkILoopInit.scala:108)
  at org.apache.spark.repl.SparkILoop.postInitialization(SparkILoop.scala:64)
  at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:991)
  at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
  at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
  at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
  at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
  at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
  at org.apache.spark.repl.Main$.main(Main.scala:31)
  at org.apache.spark.repl.Main.main(Main.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
  at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
  at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: cluster
  at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:374)
  at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
  at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
  at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:707)
  at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:650)
  at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:148)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2643)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:93)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2680)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2662)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:379)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:178)
  at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:495)
  ... 56 more
Caused by: java.net.UnknownHostException: cluster
  ... 69 more

<console>:10: error: not found: value sqlContext
       import sqlContext.implicits._
              ^
<console>:10: error: not found: value sqlContext
       import sqlContext.sql
```

**Comment by samthebest** [comment]
Using the master URL given by the UI, i.e.

```
spark-shell --master spark://ip-172-31-60-214.ec2.internal:7077
```

Results in a similar exception.

Strangely though, when I actually run a command, it does seem to actually do something:

```
sc.makeRDD(1 to 100).repartition(20).map(_ => java.lang.Thread.sleep(2000)).count()
```

**Comment by mag-** [comment]
Thanks for testing
this exception is related to missing hive configuration, I will get it fixed by configuring a local hive metastore on the master node.

**Comment by samthebest** [comment]
@mag- When I try `spark-submit` it doesn't work at all with a similar exception.  Unfortunately, unlike the spark-shell, it doesn't seem to fall through and run my job:

```
Exception in thread "main" java.lang.IllegalArgumentException: java.net.UnknownHostException: cluster
    at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:374)
    at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
    at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:707)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:650)
    at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:148)
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2643)
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:93)
    at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2680)
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2662)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:379)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:178)
    at org.apache.hadoop.mapred.JobConf.getWorkingDirectory(JobConf.java:661)
    at org.apache.hadoop.mapred.FileOutputFormat.setOutputPath(FileOutputFormat.java:146)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:987)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:897)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:896)
    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1426)
    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
    at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1405)
    at com.mendeley.altmetrics.DistributedS3Ls$.main(DistributedS3Ls.scala:29)
    at com.mendeley.altmetrics.DistributedS3Ls.main(DistributedS3Ls.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.UnknownHostException: cluster
    ... 46 more
```

:(

**Comment by mag-** [comment]
Give me a moment, will fix it properly

**Comment by mag-** [comment]
@samthebest new version in master, you can use:

```
spark-shell
```

without any arguments

**Comment by samthebest** [comment]
`spark-submit` works now too.
